#!/usr/bin/env bash
# §13 — pack the release tree, from a clean extract, reproducibly.
#
# WHAT THIS EXISTS TO PREVENT. A release built by zipping whatever happened to be in the
# working directory picks up node_modules, build output and stray probe bundles, and no two
# builds of the same commit match. This packs a NAMED tree, excludes the same set every
# time, and prints the manifest so the contents can be checked rather than assumed.
#
# Usage:  tools/pack-release.sh <source-tree> <output.zip> [version]
set -euo pipefail

SRC="${1:?usage: pack-release.sh <source-tree> <output.zip> [version]}"
OUT="${2:?usage: pack-release.sh <source-tree> <output.zip> [version]}"
VERSION="${3:-1.0.0}"

SRC="$(cd "$SRC" && pwd)"
OUT="$(cd "$(dirname "$OUT")" && pwd)/$(basename "$OUT")"

echo "== packing $VERSION"
echo "   from $SRC"
echo "   to   $OUT"

# The exclusions, each for a reason:
#   node_modules   installed dependencies — the release ships package-lock, not the tree
#   dist/target    build output, regenerated by the consumer's own build
#   .git           history is not part of a source release
#   coverage/tmp   scratch
#   *.mjs bundles  the probe runner's own throwaway output (dot-prefixed files)
EXCLUDES=(
  "*/node_modules/*" "node_modules/*"
  "*/dist/*" "dist/*"
  "*/target/*" "src-tauri/target/*"
  "*/.git/*" ".git/*"
  "*/coverage/*" "coverage/*"
  "*.DS_Store"
  "*/ocr/tessdata/*.traineddata"
  # The runner's bundles and anything a debugging session leaves behind: dot-prefixed, and
  # EXECUTABLE. Deliberately keyed on the extension rather than on the leading dot, because
  # probe/.shellRender.test.tsx.css is a real input the shell-render suite reads — a blanket
  # "probe/.*" would have dropped a fixture to catch scratch, which is its own kind of
  # wrong. The old list named bundles one by one, which is exactly how two of them shipped;
  # this catches the CLASS without catching the fixture.
  "probe/.*.mjs" "probe/.*.js" "probe/.*.cjs" "probe/.*.ts" "probe/.*.map"
  # THE RUNTIME ARTIFACTS. These are not "junk we hope nobody commits" — they are
  # files the SUITES THEMSELVES WRITE, which means a green test run puts them in
  # the tree, and this packer runs right after a green test run. agenticTest
  # writes scratch-agentic-result.json at the repo root on every pass, and the
  # browser service writes a Chromium profile directory. Both were found in a
  # real tree minutes before packing. tools/pack-release.mjs already carried the
  # same list; the two packers disagreed, and the .sh was the one that shipped.
  "scratch-agentic-result.json"
  "profiles/*" "profiles"
  "*.traineddata"
)

rm -f "$OUT"
# `-x` patterns MUST follow the file list; before it, zip has nothing to select from.
ZIP_ARGS=(-r -q -X "$OUT" .)
for e in "${EXCLUDES[@]}"; do ZIP_ARGS+=(-x "$e"); done

( cd "$SRC" && zip "${ZIP_ARGS[@]}" )

# The listing is built ONCE, before anything reads it. Piping `unzip | awk | grep -q` per
# check re-reads the archive each time, and under `set -o pipefail` an early-exiting
# `grep -q` sends SIGPIPE to the producers, so the pipeline reports 141 and a MATCH reads as
# a failure. One listing, read many times.
LIST="$(mktemp)"; trap 'rm -f "$LIST"' EXIT
unzip -l "$OUT" | awk '{print $NF}' > "$LIST"

echo
echo "== manifest"
echo "   files    $(wc -l < "$LIST")"
echo "   size     $(du -h "$OUT" | cut -f1)"
echo
echo "== the parts that matter are present"
for must in \
  "package.json" "public/ocr/tessdata/eng.traineddata.gz" "public/ocr/worker.min.js" \
  "public/ocr/core/tesseract-core-simd-lstm.wasm.js" "LICENSES/clawpdf-MIT.txt" \
  "LICENSES/tesseract.js-APACHE-2.0.txt" "src/mission/scannedPdf.ts" "src/mission/ocr.ts" \
  "probe/scanDoor.spec.ts" "verify/BUILD-INFO.txt"; do
  if grep -qx "$must" "$LIST"; then echo "   ok   $must"; else echo "   MISSING  $must"; exit 1; fi
done

echo
echo "Packed. A consumer unpacks, runs \`npm ci\`, then \`npm run test:live\` for the WASM suites"
echo "and \`npm test\` for the self-contained gate."
